### ISSUE TITLE
Making Predictions

### ISSUE THREAD

**Issue by impulsecorp** [morinim/vita#22]
I ran Vita on my dataset and the formula it output was:
[000] FADD 5.0 [033]
[033] FSUB [051] [042]
[042] FADD X78 X122
[051] FSUB [052] X78
[052] FMUL X122 X37

What is the best way for me to get predictions from that? Do you have predictions function, or a function to convert that output to standard formula format? I do understand when it says 
[000] FADD 5.0 [033]
it is saying to add 5 to formula #033, and formula #033 is shown on the next line of the results.
But I would need to write my own script to convert your formula format to a formula I can use to make actual predictions, wouldn't I?

**Comment by morinim** [comment]
I've extended the https://github.com/morinim/vita/wiki/titanic_tutorial tutorial with some details you may find interesting (please pull the update version of the repository).

It's not finished (above all it lacks information about the serialization/persistence of the lambda objects). I'm in the middle of a busy season but I hope to add further documentation/code soon.

**Comment by morinim** [comment]
Various aspects of the library has been simplified and the [tutorial](https://github.com/morinim/vita/wiki/titanic_tutorial) now describes the latest (and I hope simpler) procedure.

Further examples are in preparation, so keep an eye on the Wiki
