### ISSUE TITLE
Windows Visual Studio + CMake support/guide

### ISSUE THREAD

**Issue by DaemonIB** [morinim/vita#26]
The wiki references a Visual Studio guide as TBA. However, it doesn't seem like Vita compiles at all when generating a solution from CMake (VS19 & C++14). If it does compile, could a guide be added, and if not, document it as non-functioning.

**Comment by morinim** [comment]
At the moment I've removed Visual Studio compatibility.

The source is standard compliant so I'm quite confident a guide can be added. Perhaps minor tweaks are required (I'm working mainly under Linux as well as other known users).

Unfortunately I'm in the midst of a codebase conversion from C++14 to C++17 and I also need to improve various aspect of the `dataframe` class before considering other tasks.

Anyway Visual Studio compatibility is an important goal and I'll keep this issue open. I think I could setup a virtual machine and experiment with Visual Studio next month.

PS latest C++14 compatible version is [v1.1.0](https://github.com/morinim/vita/archive/v1.1.0.zip).

**Comment by morinim** [comment]
Things to be done:
- fix some remaining warnings;
- document the build procedure;
- use AppVeyor and integrate Visual Studio.
