### ISSUE TITLE
Usage of library file (libvita.a)

### ISSUE THREAD

**Issue by HawkTom** [morinim/vita#32]
Hello,

I want to use this library in my own project, but I didn't want to place all source files in my project. Therefore, I compile a static Library (libvita.a) as README introducing. But when I want to include it in my project, it raised errors that I didn't have the header file (The namesapces are not declared.). 

So, does it exsit one header file which includes all interfaces or I need to include all .h files in my project together with the library file.  
Thanks.

**Comment by morinim** [comment]
You can include the `vita.h` header file (`vita/src/kernel/vita.h`), it should be enough.

Anyway consider that `vita.h` is just a *group* header:

```C++
#if !defined(VITA_VITA_H)
#define      VITA_VITA_H

#include "kernel/ga/i_ga.h"
#include "kernel/ga/i_de.h"
#include "kernel/ga/primitive.h"
#include "kernel/ga/search.h"
#include "kernel/gp/mep/i_mep.h"
/// ...

#endif  // include guard
```

so you have to deploy all the other header files. There are tools to create a single header form of distribution (e.g. https://github.com/bfgroup/Lyra/blob/develop/tools/gen_single_include.py from [Lyra](https://github.com/bfgroup/Lyra/); further details [here](https://stackoverflow.com/a/63090394/3235496)).

I haven't tried this method yet. I'm going to experiment next week.

Meanwhile if you go ahead please let me know your approach.
